# Custom Language File for Launcher Customizer

[ejs.app]
title = "NexuxNova Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.nexuxnova.it"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "WELCOME TO NEXUXNOVA"
welcomeDescription = "Copyright © 2025 NexuxNova"
welcomeDescCTA = ""
